//
// Generated file, do not edit! Created by opp_msgtool 6.0 from helpers/MessageTypeTag.msg.
//

#ifndef __RLORA_MESSAGETYPETAG_M_H
#define __RLORA_MESSAGETYPETAG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace rlora {

class MessageTypeTag;

}  // namespace rlora

#include "inet/common/TagBase_m.h" // import inet.common.TagBase

// cplusplus {{
using namespace inet;
// }}


namespace rlora {

/**
 * Class generated from <tt>helpers/MessageTypeTag.msg:26</tt> by opp_msgtool.
 * <pre>
 * class MessageTypeTag extends inet::TagBase
 * {
 *     bool isNeighbourMsg;
 * }
 * </pre>
 */
class MessageTypeTag : public ::inet::TagBase
{
  protected:
    bool isNeighbourMsg_ = false;

  private:
    void copy(const MessageTypeTag& other);

  protected:
    bool operator==(const MessageTypeTag&) = delete;

  public:
    MessageTypeTag();
    MessageTypeTag(const MessageTypeTag& other);
    virtual ~MessageTypeTag();
    MessageTypeTag& operator=(const MessageTypeTag& other);
    virtual MessageTypeTag *dup() const override {return new MessageTypeTag(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual bool isNeighbourMsg() const;
    virtual void setIsNeighbourMsg(bool isNeighbourMsg);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MessageTypeTag& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MessageTypeTag& obj) {obj.parsimUnpack(b);}


}  // namespace rlora


namespace omnetpp {

template<> inline rlora::MessageTypeTag *fromAnyPtr(any_ptr ptr) { return check_and_cast<rlora::MessageTypeTag*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __RLORA_MESSAGETYPETAG_M_H

