opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 0..499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 500..999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 1000..1499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 1500..1999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 2000..2499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 2500..2999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 3000..3499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 3500..3999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 4000..4499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 4500..4999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 5000..5499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 5500..5999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 6000..6499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 6500..6999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 7000..7499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 7500..7999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 8000..8499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 8500..8999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 9000..9499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 9500..9999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 10000..10499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 10500..10999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 11000..11499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 11500..11999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 12000..12499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 12500..12999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 13000..13499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 13500..13999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 14000..14499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 14500..14999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 15000..15499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 15500..15999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 16000..16499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 16500..16999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 17000..17499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 17500..17999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 18000..18499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 18500..18999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 19000..19499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 19500..19999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 20000..20499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 20500..20999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 21000..21499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 21500..21999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 22000..22499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 22500..22999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 23000..23499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 23500..23999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 24000..24499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 24500..24999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 25000..25499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 25500..25999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 26000..26499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 26500..26999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 27000..27499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 27500..27999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 28000..28499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 28500..28999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 29000..29499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 29500..29999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 30000..30499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 30500..30999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 31000..31499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 31500..31999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 32000..32499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 32500..32999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 33000..33499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 33500..33999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 34000..34499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 34500..34999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 35000..35499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 35500..35999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 36000..36499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 36500..36999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 37000..37499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 37500..37999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 38000..38499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 38500..38999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 39000..39499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 39500..39999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 40000..40499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 40500..40999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 41000..41499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 41500..41999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 42000..42499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 42500..42999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 43000..43499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 43500..43999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 44000..44499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 44500..44999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 45000..45499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 45500..45999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 46000..46499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 46500..46999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 47000..47499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 47500..47999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 48000..48499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 48500..48999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 49000..49499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 49500..49999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 50000..50499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 50500..50999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 51000..51499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 51500..51999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 52000..52499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 52500..52999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 53000..53499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 53500..53999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 54000..54499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 54500..54999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 55000..55499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 55500..55999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 56000..56499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 56500..56999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 57000..57499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 57500..57999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 58000..58499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 58500..58999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 59000..59499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 59500..59999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 60000..60499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 60500..60999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 61000..61499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 61500..61999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 62000..62499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 62500..62999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 63000..63499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 63500..63999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 64000..64499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 64500..64999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 65000..65499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 65500..65999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 66000..66499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 66500..66999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 67000..67499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 67500..67999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 68000..68499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 68500..68999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 69000..69499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 69500..69999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 70000..70499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 70500..70999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 71000..71499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 71500..71999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 72000..72499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 72500..72999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 73000..73499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 73500..73999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 74000..74499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 74500..74999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 75000..75499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 75500..75999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 76000..76499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 76500..76999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 77000..77499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 77500..77999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 78000..78499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 78500..78999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 79000..79499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 79500..79999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 80000..80499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 80500..80999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 81000..81499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 81500..81999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 82000..82499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 82500..82999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 83000..83499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 83500..83999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 84000..84499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 84500..84999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 85000..85499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 85500..85999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 86000..86499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 86500..86999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 87000..87499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 87500..87999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 88000..88499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 88500..88999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 89000..89499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 89500..89999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 90000..90499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 90500..90999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 91000..91499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 91500..91999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 92000..92499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 92500..92999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 93000..93499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 93500..93999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 94000..94499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 94500..94999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 95000..95499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 95500..95999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 96000..96499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 96500..96999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 97000..97499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 97500..97999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 98000..98499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 98500..98999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 99000..99499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 99500..99999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 100000..100499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 100500..100999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 101000..101499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 101500..101999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 102000..102499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 102500..102999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 103000..103499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 103500..103999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 104000..104499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 104500..104999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 105000..105499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 105500..105999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 106000..106499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 106500..106999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 107000..107499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 107500..107999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 108000..108499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 108500..108999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 109000..109499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 109500..109999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 110000..110499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 110500..110999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 111000..111499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 111500..111999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 112000..112499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 112500..112999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 113000..113499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 113500..113999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 114000..114499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 114500..114999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 115000..115499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 115500..115999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 116000..116499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 116500..116999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 117000..117499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 117500..117999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 118000..118499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 118500..118999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 119000..119499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 119500..119999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 120000..120499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 120500..120999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 121000..121499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 121500..121999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 122000..122499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 122500..122999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 123000..123499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 123500..123999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 124000..124499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 124500..124999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 125000..125499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 125500..125999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 126000..126499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 126500..126999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 127000..127499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 127500..127999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 128000..128499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 128500..128999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 129000..129499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 129500..129999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 130000..130499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 130500..130999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 131000..131499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 131500..131999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 132000..132499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 132500..132999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 133000..133499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 133500..133999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 134000..134499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 134500..134999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 135000..135499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 135500..135999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 136000..136499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 136500..136999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 137000..137499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 137500..137999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 138000..138499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 138500..138999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 139000..139499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 139500..139999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 140000..140499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 140500..140999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 141000..141499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 141500..141999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 142000..142499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 142500..142999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 143000..143499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 143500..143999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 144000..144499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 144500..144999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 145000..145499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 145500..145999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 146000..146499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 146500..146999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 147000..147499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 147500..147999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 148000..148499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 148500..148999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 149000..149499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 149500..149999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 150000..150499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 150500..150999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 151000..151499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 151500..151999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 152000..152499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 152500..152999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 153000..153499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 153500..153599
