opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 0..499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 500..999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 1000..1499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 1500..1999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 2000..2499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 2500..2999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 3000..3499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 3500..3999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 4000..4499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 4500..4999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 5000..5499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 5500..5999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 6000..6499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 6500..6999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 7000..7499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 7500..7999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 8000..8499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 8500..8999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 9000..9499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 9500..9999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 10000..10499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 10500..10999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 11000..11499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 11500..11999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 12000..12499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 12500..12999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 13000..13499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 13500..13999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 14000..14499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 14500..14999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 15000..15499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 15500..15999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 16000..16499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 16500..16999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 17000..17499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 17500..17999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 18000..18499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 18500..18999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 19000..19499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 19500..19999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 20000..20499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 20500..20999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 21000..21499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 21500..21999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 22000..22499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 22500..22999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 23000..23499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 23500..23999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 24000..24499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 24500..24999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 25000..25499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 25500..25999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 26000..26499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 26500..26999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 27000..27499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 27500..27999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 28000..28499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 28500..28999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 29000..29499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 29500..29999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 30000..30499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 30500..30999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 31000..31499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 31500..31999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 32000..32499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 32500..32999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 33000..33499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 33500..33999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 34000..34499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 34500..34999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 35000..35499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 35500..35999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 36000..36499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 36500..36999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 37000..37499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 37500..37999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 38000..38499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 38500..38999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 39000..39499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 39500..39999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 40000..40499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 40500..40999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 41000..41499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 41500..41999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 42000..42499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 42500..42999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 43000..43499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 43500..43999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 44000..44499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 44500..44999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 45000..45499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 45500..45999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 46000..46499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 46500..46999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 47000..47499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 47500..47999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 48000..48499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 48500..48999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 49000..49499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 49500..49999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 50000..50499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 50500..50999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 51000..51499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 51500..51999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 52000..52499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 52500..52999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 53000..53499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 53500..53999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 54000..54499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 54500..54999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 55000..55499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 55500..55999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 56000..56499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 56500..56999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 57000..57499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 57500..57999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 58000..58499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 58500..58999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 59000..59499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 59500..59999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 60000..60499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 60500..60999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 61000..61499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 61500..61999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 62000..62499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 62500..62999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 63000..63499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 63500..63999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 64000..64499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 64500..64999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 65000..65499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 65500..65999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 66000..66499
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 66500..66999
opp_runall -j80 ./out/clang-release/src/rlora -f ./simulations/omnetpp.ini -c MassMobility -u Cmdenv -n ./simulations:./src:./../inet4.4/src -l ./../inet4.4/src/INET -r 67000..67199
