//
// Generated file, do not edit! Created by opp_msgtool 6.0 from LoRaCSMA/BroadcastLeaderFragment.msg.
//

#ifndef __RLORA_BROADCASTLEADERFRAGMENT_M_H
#define __RLORA_BROADCASTLEADERFRAGMENT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace rlora {

class BroadcastLeaderFragment;

}  // namespace rlora

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/common/Units_m.h" // import inet.common.Units

// cplusplus {{
using namespace inet;
// }}


namespace rlora {

/**
 * Class generated from <tt>LoRaCSMA/BroadcastLeaderFragment.msg:29</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * class BroadcastLeaderFragment extends inet::FieldsChunk
 * {
 *     int source;
 *     int hop;
 *     int messageId;
 *     int size;
 *     int payloadSize;
 *     bool retransmit;
 * }
 * </pre>
 */
class BroadcastLeaderFragment : public ::inet::FieldsChunk
{
  protected:
    int source = 0;
    int hop = 0;
    int messageId = 0;
    int size = 0;
    int payloadSize = 0;
    bool retransmit = false;

  private:
    void copy(const BroadcastLeaderFragment& other);

  protected:
    bool operator==(const BroadcastLeaderFragment&) = delete;

  public:
    BroadcastLeaderFragment();
    BroadcastLeaderFragment(const BroadcastLeaderFragment& other);
    virtual ~BroadcastLeaderFragment();
    BroadcastLeaderFragment& operator=(const BroadcastLeaderFragment& other);
    virtual BroadcastLeaderFragment *dup() const override {return new BroadcastLeaderFragment(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSource() const;
    virtual void setSource(int source);

    virtual int getHop() const;
    virtual void setHop(int hop);

    virtual int getMessageId() const;
    virtual void setMessageId(int messageId);

    virtual int getSize() const;
    virtual void setSize(int size);

    virtual int getPayloadSize() const;
    virtual void setPayloadSize(int payloadSize);

    virtual bool getRetransmit() const;
    virtual void setRetransmit(bool retransmit);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BroadcastLeaderFragment& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BroadcastLeaderFragment& obj) {obj.parsimUnpack(b);}


}  // namespace rlora


namespace omnetpp {

template<> inline rlora::BroadcastLeaderFragment *fromAnyPtr(any_ptr ptr) { return check_and_cast<rlora::BroadcastLeaderFragment*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __RLORA_BROADCASTLEADERFRAGMENT_M_H

