//
// Generated file, do not edit! Created by opp_msgtool 6.0 from LoRaApp/LoRaRobotPacket.msg.
//

#ifndef __RLORA_LORAROBOTPACKET_M_H
#define __RLORA_LORAROBOTPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace rlora {

class LoRaOptions;
class LoRaRobotPacket;

}  // namespace rlora

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace rlora {

/**
 * Class generated from <tt>LoRaApp/LoRaRobotPacket.msg:21</tt> by opp_msgtool.
 * <pre>
 * class LoRaOptions
 * {
 *     double LoRaTP = -1;
 *     double LoRaCF = -1;
 *     int LoRaSF = -1;
 *     double LoRaBW = -1;
 *     int LoRaCR = -1;
 *     bool UseHeader = true;
 *     bool ADRACKReq = false;
 * }
 * </pre>
 */
class LoRaOptions
{
  protected:
    double LoRaTP = -1;
    double LoRaCF = -1;
    int LoRaSF = -1;
    double LoRaBW = -1;
    int LoRaCR = -1;
    bool UseHeader = true;
    bool ADRACKReq = false;

  private:
    void copy(const LoRaOptions& other);

  protected:
    bool operator==(const LoRaOptions&) = delete;

  public:
    LoRaOptions();
    LoRaOptions(const LoRaOptions& other);
    virtual ~LoRaOptions();
    LoRaOptions& operator=(const LoRaOptions& other);
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    virtual double getLoRaTP() const;
    virtual void setLoRaTP(double LoRaTP);

    virtual double getLoRaCF() const;
    virtual void setLoRaCF(double LoRaCF);

    virtual int getLoRaSF() const;
    virtual void setLoRaSF(int LoRaSF);

    virtual double getLoRaBW() const;
    virtual void setLoRaBW(double LoRaBW);

    virtual int getLoRaCR() const;
    virtual void setLoRaCR(int LoRaCR);

    virtual bool getUseHeader() const;
    virtual void setUseHeader(bool UseHeader);

    virtual bool getADRACKReq() const;
    virtual void setADRACKReq(bool ADRACKReq);
};

/**
 * Class generated from <tt>LoRaApp/LoRaRobotPacket.msg:34</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * class LoRaRobotPacket extends inet::FieldsChunk
 * {
 *     LoRaOptions options;
 * }
 * </pre>
 */
class LoRaRobotPacket : public ::inet::FieldsChunk
{
  protected:
    LoRaOptions options;

  private:
    void copy(const LoRaRobotPacket& other);

  protected:
    bool operator==(const LoRaRobotPacket&) = delete;

  public:
    LoRaRobotPacket();
    LoRaRobotPacket(const LoRaRobotPacket& other);
    virtual ~LoRaRobotPacket();
    LoRaRobotPacket& operator=(const LoRaRobotPacket& other);
    virtual LoRaRobotPacket *dup() const override {return new LoRaRobotPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const LoRaOptions& getOptions() const;
    virtual LoRaOptions& getOptionsForUpdate() { handleChange();return const_cast<LoRaOptions&>(const_cast<LoRaRobotPacket*>(this)->getOptions());}
    virtual void setOptions(const LoRaOptions& options);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LoRaRobotPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LoRaRobotPacket& obj) {obj.parsimUnpack(b);}


}  // namespace rlora


namespace omnetpp {

inline any_ptr toAnyPtr(const rlora::LoRaOptions *p) {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
template<> inline rlora::LoRaOptions *fromAnyPtr(any_ptr ptr) { return ptr.get<rlora::LoRaOptions>(); }
template<> inline rlora::LoRaRobotPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<rlora::LoRaRobotPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __RLORA_LORAROBOTPACKET_M_H

