//
// Generated file, do not edit! Created by opp_msgtool 6.0 from LoRaMeshRouter/BroadcastAck.msg.
//

#ifndef __RLORA_BROADCASTACK_M_H
#define __RLORA_BROADCASTACK_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace rlora {

class BroadcastAck;

}  // namespace rlora

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace rlora {

/**
 * Class generated from <tt>LoRaMeshRouter/BroadcastAck.msg:23</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * class BroadcastAck extends inet::FieldsChunk
 * {
 * }
 * </pre>
 */
class BroadcastAck : public ::inet::FieldsChunk
{
  protected:

  private:
    void copy(const BroadcastAck& other);

  protected:
    bool operator==(const BroadcastAck&) = delete;

  public:
    BroadcastAck();
    BroadcastAck(const BroadcastAck& other);
    virtual ~BroadcastAck();
    BroadcastAck& operator=(const BroadcastAck& other);
    virtual BroadcastAck *dup() const override {return new BroadcastAck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BroadcastAck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BroadcastAck& obj) {obj.parsimUnpack(b);}


}  // namespace rlora


namespace omnetpp {

template<> inline rlora::BroadcastAck *fromAnyPtr(any_ptr ptr) { return check_and_cast<rlora::BroadcastAck*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __RLORA_BROADCASTACK_M_H

