//
// Generated file, do not edit! Created by opp_msgtool 6.0 from LoRaMeshRouter/BroadcastFragment.msg.
//

#ifndef __RLORA_BROADCASTFRAGMENT_M_H
#define __RLORA_BROADCASTFRAGMENT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace rlora {

class BroadcastFragment;

}  // namespace rlora

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace rlora {

/**
 * Class generated from <tt>LoRaMeshRouter/BroadcastFragment.msg:23</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * class BroadcastFragment extends inet::FieldsChunk
 * {
 *     int messageId;
 *     int fragment;
 *     int size;
 *     int source;
 * }
 * </pre>
 */
class BroadcastFragment : public ::inet::FieldsChunk
{
  protected:
    int messageId = 0;
    int fragment = 0;
    int size = 0;
    int source = 0;

  private:
    void copy(const BroadcastFragment& other);

  protected:
    bool operator==(const BroadcastFragment&) = delete;

  public:
    BroadcastFragment();
    BroadcastFragment(const BroadcastFragment& other);
    virtual ~BroadcastFragment();
    BroadcastFragment& operator=(const BroadcastFragment& other);
    virtual BroadcastFragment *dup() const override {return new BroadcastFragment(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getMessageId() const;
    virtual void setMessageId(int messageId);

    virtual int getFragment() const;
    virtual void setFragment(int fragment);

    virtual int getSize() const;
    virtual void setSize(int size);

    virtual int getSource() const;
    virtual void setSource(int source);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BroadcastFragment& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BroadcastFragment& obj) {obj.parsimUnpack(b);}


}  // namespace rlora


namespace omnetpp {

template<> inline rlora::BroadcastFragment *fromAnyPtr(any_ptr ptr) { return check_and_cast<rlora::BroadcastFragment*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __RLORA_BROADCASTFRAGMENT_M_H

