//
// Generated file, do not edit! Created by opp_msgtool 6.0 from LoRaMeshRouter/NodeAnnounce.msg.
//

#ifndef __RLORA_NODEANNOUNCE_M_H
#define __RLORA_NODEANNOUNCE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace rlora {

class NodeAnnounce;

}  // namespace rlora

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace rlora {

/**
 * Class generated from <tt>LoRaMeshRouter/NodeAnnounce.msg:23</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * class NodeAnnounce extends inet::FieldsChunk
 * {
 *     int nodeId;
 *     int lastHop;
 *     int respond;
 * }
 * </pre>
 */
class NodeAnnounce : public ::inet::FieldsChunk
{
  protected:
    int nodeId = 0;
    int lastHop = 0;
    int respond = 0;

  private:
    void copy(const NodeAnnounce& other);

  protected:
    bool operator==(const NodeAnnounce&) = delete;

  public:
    NodeAnnounce();
    NodeAnnounce(const NodeAnnounce& other);
    virtual ~NodeAnnounce();
    NodeAnnounce& operator=(const NodeAnnounce& other);
    virtual NodeAnnounce *dup() const override {return new NodeAnnounce(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getNodeId() const;
    virtual void setNodeId(int nodeId);

    virtual int getLastHop() const;
    virtual void setLastHop(int lastHop);

    virtual int getRespond() const;
    virtual void setRespond(int respond);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const NodeAnnounce& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, NodeAnnounce& obj) {obj.parsimUnpack(b);}


}  // namespace rlora


namespace omnetpp {

template<> inline rlora::NodeAnnounce *fromAnyPtr(any_ptr ptr) { return check_and_cast<rlora::NodeAnnounce*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __RLORA_NODEANNOUNCE_M_H

