//
// Generated file, do not edit! Created by opp_msgtool 6.0 from LoRaMeshRouter/WaitTimeTag.msg.
//

#ifndef __RLORA_WAITTIMETAG_M_H
#define __RLORA_WAITTIMETAG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace rlora {

class WaitTimeTag;

}  // namespace rlora

#include "inet/common/TagBase_m.h" // import inet.common.TagBase

// cplusplus {{
using namespace inet;
// }}


namespace rlora {

/**
 * Class generated from <tt>LoRaMeshRouter/WaitTimeTag.msg:25</tt> by opp_msgtool.
 * <pre>
 * class WaitTimeTag extends inet::TagBase
 * {
 *     int waitTime;
 * }
 * </pre>
 */
class WaitTimeTag : public ::inet::TagBase
{
  protected:
    int waitTime = 0;

  private:
    void copy(const WaitTimeTag& other);

  protected:
    bool operator==(const WaitTimeTag&) = delete;

  public:
    WaitTimeTag();
    WaitTimeTag(const WaitTimeTag& other);
    virtual ~WaitTimeTag();
    WaitTimeTag& operator=(const WaitTimeTag& other);
    virtual WaitTimeTag *dup() const override {return new WaitTimeTag(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getWaitTime() const;
    virtual void setWaitTime(int waitTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const WaitTimeTag& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, WaitTimeTag& obj) {obj.parsimUnpack(b);}


}  // namespace rlora


namespace omnetpp {

template<> inline rlora::WaitTimeTag *fromAnyPtr(any_ptr ptr) { return check_and_cast<rlora::WaitTimeTag*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __RLORA_WAITTIMETAG_M_H

